//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_transaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockremain
    {
        public int id { get; set; }
        public string account { get; set; }
        public string 證券代號 { get; set; }
        public string 證券名稱 { get; set; }
        public string 成交均價 { get; set; }
        public string 張數 { get; set; }
        public string 持有成本 { get; set; }
        public string 現價 { get; set; }
        public string 現值 { get; set; }
        public string 預估收入 { get; set; }
        public string 預估損益 { get; set; }
        public string 預估獲利率 { get; set; }
    }
}
